name: dartchess
description: Chess rules library for native platforms.
repository: https://github.com/lichess-org/dartchess
version: 0.1.0
platforms:
  android:
  ios:
  linux:
  macos:
  windows:
funding:
  - https://lichess.org/patron

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  fast_immutable_collections: ^9.0.0
  meta: ^1.8.0

dev_dependencies:
  benchmark: ^0.3.0
  lint: ^2.0.1
  test: ^1.16.0
